# Generated by Django 4.1.5 on 2023-01-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.TextField(default='short_description', max_length=100),
            preserve_default=False,
        ),
    ]
