# Generated by Django 4.1.5 on 2023-01-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('issue_date', models.DateTimeField()),
                ('technology', models.CharField(max_length=60)),
                ('workload', models.PositiveIntegerField()),
                ('image', models.FilePathField(path='/img')),
            ],
        ),
    ]
