# Generated by Django 4.1.5 on 2023-01-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0002_alter_certification_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='issue_date',
            field=models.DateField(),
        ),
    ]
