# Generated by Django 4.1.5 on 2023-01-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0003_alter_certification_issue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='description',
            field=models.TextField(default='description'),
            preserve_default=False,
        ),
    ]
