# Generated by Django 4.1.5 on 2023-01-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0004_certification_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='url',
            field=models.URLField(default='http://www.freecodecamp.com'),
            preserve_default=False,
        ),
    ]
