# Generated by Django 4.1.7 on 2023-02-25 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('issue_date', models.DateField()),
                ('technology', models.CharField(max_length=60)),
                ('workload', models.PositiveIntegerField()),
                ('image', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
    ]
