# Generated by Django 4.1.7 on 2023-02-25 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('short_description', models.TextField(max_length=100)),
                ('technology', models.CharField(max_length=60)),
                ('image', models.CharField(max_length=100)),
            ],
        ),
    ]
