# Generated by Django 4.1.7 on 2023-02-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='live_url',
            field=models.URLField(default='https://www.dirkmeer.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='source_url',
            field=models.URLField(blank=True),
        ),
    ]
