# Generated by Django 4.1.5 on 2023-01-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0005_certification_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='short_description',
            field=models.CharField(default='short description', max_length=200),
            preserve_default=False,
        ),
    ]
