# Generated by Django 4.1.5 on 2023-01-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0006_certification_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='image',
            field=models.FilePathField(path='/img/'),
        ),
    ]
