# Generated by Django 4.1.5 on 2023-01-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0008_alter_certification_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='image',
            field=models.FilePathField(path='certifications/static/img'),
        ),
    ]
